### PR TITLE
test that clicking the menu opens the navbar on a small window

### PR DESCRIPTION
**Pull request by mcassano**

### CODE REVIEW

**Comment by notmarkmiranda** [comment]
Does this pass for you locally? I've got a failure on your test.

image

**Review by notmarkmiranda — CHANGES_REQUESTED** [review]
fails

**Comment by mcassano** [comment]
@notmarkmiranda I pushed a revision, can you try that?  Maybe due to our different systems preferences bootstrap didn't give you a hamburger to click.

**Comment by mcassano** [comment]
converting to draft, I'll figure out why the test is flaky

**Comment by mcassano** [comment]
not worth it

**Pull request closed without merging**
